spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdw2024
    username: root
    password: 193244
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
  application:
    name: santander-dev-week-2024
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false